#ifndef PINS_H
#define PINS_H

#define DISCOVERY_LD3 GPIO_Pin_9
#define DISCOVERY_LD3_PORT GPIOE
#define DISCOVERY_LD4 GPIO_Pin_8
#define DISCOVERY_LD4_PORT GPIOE
#define DISCOVERY_LD5 GPIO_Pin_10
#define DISCOVERY_LD5_PORT GPIOE
#define DISCOVERY_LD6 GPIO_Pin_15
#define DISCOVERY_LD6_PORT GPIOE
#define DISCOVERY_LD7 GPIO_Pin_11
#define DISCOVERY_LD7_PORT GPIOE
#define DISCOVERY_LD8 GPIO_Pin_14
#define DISCOVERY_LD8_PORT GPIOE
#define DISCOVERY_LD9 GPIO_Pin_12
#define DISCOVERY_LD9_PORT GPIOE
#define DISCOVERY_LD10 GPIO_Pin_13
#define DISCOVERY_LD10_PORT GPIOE

#endif